# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rcpg.proto for package 'rcpg'

require 'grpc'
require 'rcpg_pb'

module Rcpg
  module PaymentGatewayGrpc
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rcpg.PaymentGatewayGrpc'

      # Initiates either Authorize or Purchase action. Initiation can only be cardless.
      rpc :InitiateCardless, InitiateCardlessRequest, InitiateCardlessResponse
      # Based on intent executes either Authorize or Purchase action for standard payment.
      rpc :PayStandard, PayStandardRequest, PayResponse
      # Based on intent executes either Authorize or Purchase action for cardless payment.
      rpc :PayCardless, PayCardlessRequest, PayResponse
      # Can capture both cardless and standard authorization.
      rpc :Capture, CaptureRequest, PayResponse
      # Gets payment details by token or transaction. Only supported by PayPal Express Checkout.
      rpc :GetDetails, GetDetailsRequest, GetDetailsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
