# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rcpg.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "rcpg.InitiateCardlessRequest" do
    optional :provider, :enum, 1, "rcpg.Provider"
    optional :payment_sum, :int32, 2
    optional :currency, :string, 3
    optional :intent, :enum, 4, "rcpg.Intent"
    optional :return_url, :string, 5
    optional :cancel_return_url, :string, 6
    optional :allow_guest_checkout, :bool, 7
    repeated :items, :message, 8, "rcpg.Item"
  end
  add_message "rcpg.PayStandardRequest" do
    optional :provider, :enum, 1, "rcpg.Provider"
    optional :payment_sum, :int32, 2
    optional :currency, :string, 3
    optional :payment_card, :message, 4, "rcpg.PaymentCard"
    optional :intent, :enum, 5, "rcpg.Intent"
    repeated :items, :message, 6, "rcpg.Item"
  end
  add_message "rcpg.PayCardlessRequest" do
    optional :provider, :enum, 1, "rcpg.Provider"
    optional :payment_sum, :int32, 2
    optional :currency, :string, 3
    optional :payment_id, :string, 4
    optional :payer_id, :string, 5
    optional :intent, :enum, 6, "rcpg.Intent"
  end
  add_message "rcpg.CaptureRequest" do
    optional :provider, :enum, 1, "rcpg.Provider"
    optional :payment_sum, :int32, 2
    optional :currency, :string, 3
    optional :payment_id, :string, 4
  end
  add_message "rcpg.GetDetailsRequest" do
    optional :provider, :enum, 1, "rcpg.Provider"
    optional :identifier, :string, 2
    optional :id_type, :enum, 3, "rcpg.PaymentIdType"
  end
  add_message "rcpg.InitiateCardlessResponse" do
    repeated :payment_errors, :message, 1, "rcpg.PaymentError"
    optional :token, :string, 2
    optional :confirm_initiation_url, :string, 3
    optional :initiated_on, :string, 4
  end
  add_message "rcpg.PayResponse" do
    repeated :payment_errors, :message, 1, "rcpg.PaymentError"
    optional :payment_id, :string, 2
    optional :executed_on, :string, 3
  end
  add_message "rcpg.GetDetailsResponse" do
    repeated :errors, :message, 1, "rcpg.PaymentError"
    optional :details, :string, 2
  end
  add_message "rcpg.PaymentCard" do
    optional :primary_number, :string, 1
    optional :first_name, :string, 2
    optional :last_name, :string, 3
    optional :month, :string, 4
    optional :year, :int32, 5
    optional :verification_value, :string, 6
  end
  add_message "rcpg.Item" do
    optional :name, :string, 1
    optional :description, :string, 2
    optional :quantity, :int32, 3
    optional :amount, :int32, 4
  end
  add_message "rcpg.PaymentError" do
    optional :source, :string, 1
    optional :error_code, :string, 2
  end
  add_enum "rcpg.Provider" do
    value :NO_PROVIDER, 0
    value :PaypalExpressGateway, 1
    value :AuthorizeNetGateway, 2
  end
  add_enum "rcpg.Intent" do
    value :NO_INTENT, 0
    value :PURCHASE, 1
    value :AUTHORIZATION, 2
  end
  add_enum "rcpg.PaymentIdType" do
    value :NO_IDENTIFIER_TYPE, 0
    value :TOKEN, 1
    value :TRANSACTION_ID, 2
  end
end

module Rcpg
  InitiateCardlessRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.InitiateCardlessRequest").msgclass
  PayStandardRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.PayStandardRequest").msgclass
  PayCardlessRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.PayCardlessRequest").msgclass
  CaptureRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.CaptureRequest").msgclass
  GetDetailsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.GetDetailsRequest").msgclass
  InitiateCardlessResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.InitiateCardlessResponse").msgclass
  PayResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.PayResponse").msgclass
  GetDetailsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.GetDetailsResponse").msgclass
  PaymentCard = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.PaymentCard").msgclass
  Item = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.Item").msgclass
  PaymentError = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.PaymentError").msgclass
  Provider = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.Provider").enummodule
  Intent = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.Intent").enummodule
  PaymentIdType = Google::Protobuf::DescriptorPool.generated_pool.lookup("rcpg.PaymentIdType").enummodule
end
